# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gen < Formula
  desc "A Swiss Army knife CLI tool for developers, packed with useful utilities for daily tasks."
  homepage "https://github.com/aminshahid573/gen"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.5/gen_darwin_amd64.tar.gz"
      sha256 "60b60cbe3a5c6e60ef8c748e5e4ded98f9af754f457617657cd08abf576592ae"

      define_method(:install) do
        bin.install "gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.5/gen_darwin_arm64.tar.gz"
      sha256 "6c7de666b9425e968d6a3d77b64c3c9980d5cada5a3d6f146b184979834fd91c"

      define_method(:install) do
        bin.install "gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.5/gen_linux_amd64.tar.gz"
      sha256 "cf05b73d0243fda4a5e2e24c385926b299c6974ae24c256bef0db83517596eaa"
      define_method(:install) do
        bin.install "gen"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.5/gen_linux_armv6.tar.gz"
      sha256 "69e42ca17bf638494815a8ee89ea9adfdfa6bdcf515f116eeac47e72f056ce7c"
      define_method(:install) do
        bin.install "gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.5/gen_linux_arm64.tar.gz"
      sha256 "7bb5cfe30ab59a76fe3fb4b4944e5f331fd0e9232177a1524b7825ef539246dd"
      define_method(:install) do
        bin.install "gen"
      end
    end
  end

  test do
    system "#{bin}/gen --version"
  end
end
