# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gen < Formula
  desc "A Swiss Army knife CLI tool for developers, packed with useful utilities for daily tasks."
  homepage "https://github.com/aminshahid573/gen"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.4/gen_darwin_amd64.tar.gz"
      sha256 "0a9ceaf8e485f1798a06fc4d245dad12b3a1a213c48e30b8eacfcb9886a83a0c"

      define_method(:install) do
        bin.install "gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.4/gen_darwin_arm64.tar.gz"
      sha256 "f61ff53d3901084b021ac9752f6fbc935e0f6cc6e92d9d8974511d802de7a3f5"

      define_method(:install) do
        bin.install "gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.4/gen_linux_amd64.tar.gz"
      sha256 "2e394bb4072cfd80e7b205c92d2d93013432356111919e169606bbe81c9f0b4d"
      define_method(:install) do
        bin.install "gen"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.4/gen_linux_armv6.tar.gz"
      sha256 "7a6c5127dba5cb337d7e655b27c1435404030b1d9a9319041a7818a686f9fabb"
      define_method(:install) do
        bin.install "gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aminshahid573/gen/releases/download/v1.0.4/gen_linux_arm64.tar.gz"
      sha256 "9ddbbdcb56786b60342be040cd49e33a980628f1abac68b2a57246bd3ca597a4"
      define_method(:install) do
        bin.install "gen"
      end
    end
  end

  test do
    system "#{bin}/gen --version"
  end
end
